### ISSUE TITLE
Error during precompiling

### ISSUE THREAD

**Issue by andoriyu** [tors/jquery-fileupload-rails#10]
bundle exec rake assets:precompile                                                                                                                                        15:12:04
/Users/andoriyu/.rvm/rubies/ruby-1.9.3-p194/bin/ruby /Users/andoriyu/.rvm/gems/ruby-1.9.3-p194/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
rake aborted!
Invalid CSS after "*": expected "{", was "html .fileinput..."

"html" may only be used at the beginning of a selector.
  (in /Users/andoriyu/Git/Ruby/sarp/app/assets/stylesheets/application.scss)

Tasks: TOP => assets:precompile:primary
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [/Users/andoriyu/.rvm/rubies/ruby-1.9.3-p19...]

Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

**Comment by felixbuenemann** [comment]
As written above: upgrade sass.
