### ISSUE TITLE
File name uniqueness

### ISSUE THREAD

**Issue by grub4r** [tors/jquery-fileupload-rails#27]
When i upload a file with the same name as an existing file, i get a rollback on the create action.
But when ajax reloads the index-action, it seem to show that the file got uploaded but with an "Internal Server Error" box.

At the index loading process i get :

ERROR NoMethodError: undefined method `bytesize' for :datafile_file_name:Symbol

**Comment by st118173** [comment]
Hello

**Comment by st118173** [comment]
@grub4r hello

**Comment by st118173** [comment]
![credit-card](https://cloud.githubusercontent.com/assets/22965252/20019190/a3735a60-a2fd-11e6-945f-1184c500008a.png)
