### ISSUE TITLE
example app not working with 0.4.1 gem

### ISSUE THREAD

**Issue by adejoux** [tors/jquery-fileupload-rails#30]
Hello,

The example app is working fine with 0.4.0 version but the 0.4.1 seems to broke something.

In console, ('#fileupload').data('fileupload') return undefined and we see a "Error Empty file upload result" when trying to upload.

Working perfectly fine in 0.4.0 version.

**Comment by AmitPatel-BoTreeConsulting** [comment]
I am facing this issue. 

I cloned @digitalfrost 's PR and upgraded to rails 4.2.4 and jquery-fileupload-rails 0.4.5.

**Comment by Praveenkumar-Invoscape** [comment]
I am also facing that same issue anyone give some ideas to solve that

**Comment by sarink** [comment]
This issue was opened and answered in 2013, Rails 4 didn't even exist then! I think you're on your own...
