### ISSUE TITLE
This gem does not suppoort I18N localization properly

### ISSUE THREAD

**Issue by raydog153** [tors/jquery-fileupload-rails#31]
In the javascript files (jquery-fileupload-ui.js, maybe others as well) there are hard coded strings for error handling and other display text. There is a local.js file, but that is never used. It would be great if the local file was implemented so I could provide a locale file for other locales for full I18n support.

**Comment by felixbuenemann** [comment]
You should report his to the original repository: blueimp/jQuery-File-Upload
