### ISSUE TITLE
Update required to fix IE10 double click issue?

### ISSUE THREAD

**Issue by jamesburke-examtime** [tors/jquery-fileupload-rails#33]
See https://github.com/blueimp/jQuery-File-Upload/issues/1611

Symptoms: Clicking the add file button requires a double click in IE 10.

This issue is occurring for me when using this gem, but seems fixed in the main jquery-file-upload repo. Perhaps this gem needs updated?

Thanks

**Comment by felixbuenemann** [comment]
Is this still an issue with 0.4.2?

**Comment by felixbuenemann** [comment]
Please open a new issue if this still happens with 0.4.2.
