### ISSUE TITLE
0.4.1 scss breaks projects not using `sass`

### ISSUE THREAD

**Issue by troex** [tors/jquery-fileupload-rails#35]
I'm using `less` in my rails projects and as follows cannot compile `vendor/assets/stylesheets/jquery.fileupload-ui.scss`, please revert to erb or add `sass` dependency to gemspec. ERB looks like a more flexible solution to me

**Comment by felixbuenemann** [comment]
@opti @tors What do you think, we should probably add a dependency on `'sass', '~> 3.2'` to the gemspec.

**Comment by tors** [comment]
@felixbuenemann I'll add the sass dependency. Thanks @felixbuenemann!
