### ISSUE TITLE
TypeError: data.context is undefined ,  data.context.find('.preview span').each(function (index, element) {

### ISSUE THREAD

**Issue by rajeev37** [tors/jquery-fileupload-rails#41]
Showing an error when uploading a single file.

     $(document).ready(function() {
        profile_services();
      call_upload('fileupload', #{@user.id}, 'template-upload', 'template-download')
      function call_upload(id, u_id, u_temp, d_temp) {
      // Initialize the jQuery File Upload widget:
        $('#fileupload').fileupload({autoUpload: true, uploadTemplateId: u_temp, downloadTemplateId: d_temp, _renderPreviews: renderPreviews, done: uploadDone, destroy: destroyDone, add: uploadPreview, maxFileSize: 5000000, acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i });
        $('#fileupload').bind('fileuploadsend', function(event, data) {
          auth_token = $('meta[name="csrf-token"]').attr('content');
          data.url = data.url + '?authenticity_token=' + encodeURIComponent(auth_token);
          $.blueimp.fileupload.prototype.options.send.call(this, event, data);
        });
        // Load existing files:
        $.getJSON($('#fileupload').prop('action'), function (files) {
          console.log(files);
          var fu = $('#fileupload').data('blueimpFileupload') ||$("#fileupload").data('fileupload'),template;
          fu._adjustMaxNumberOfFiles(-files.length);
          console.log(files);

          template = fu._renderDownload(files).appendTo($('#fileupload .files'));
          console.log(template);
          // Force reflow:
          fu._reflow = fu._transition && template.length && template[0].offsetWidth;
          template.addClass('in');
          $('#loading').remove();
      });
      }
      function uploadDone(e, data) {
        var that = $(this).data('blueimp-fileupload') || $(this).data('fileupload'),
            files = that._getFilesFromResponse(data),
            template,
            deferred;
        if (data.context) {
            data.context.each(function (index) {
                var file = files[index] || {error: 'Empty file upload result'},
                    deferred = that._addFinishedDeferreds();
                if (file.error) {
                    that._adjustMaxNumberOfFiles(1);
                }
                that._transition($(this)).done(
                    function () {
                        var node = $(this);
                        $('#fileupload .template-download').remove();
                        $('#fileupload .btn-success span').html('Change');
                        template = that._renderDownload([file]).replaceAll(node);
                        that._forceReflow(template);
                        that._transition(template).done(
                            function () {
                                data.context = $(this);
                                that._trigger('completed', e, data);
                                that._trigger('finished', e, data);
                                deferred.resolve();
                            }
                        );
                    }
                );
            });
        } else {
            if (files.length) {
                $.each(files, function (index, file) {
                    if (data.maxNumberOfFilesAdjusted && file.error) {
                        that._adjustMaxNumberOfFiles(1);
                    } else if (!data.maxNumberOfFilesAdjusted &&
                            !file.error) {
                        that._adjustMaxNumberOfFiles(-1);
                    }
                });
                data.maxNumberOfFilesAdjusted = true;
            }
            template = that._renderDownload(files)
                .appendTo(that.options.filesContainer);
            that._forceReflow(template);
            deferred = that._addFinishedDeferreds();
            that._transition(template).done(
                function () {
                    data.context = $(this);
                    that._trigger('completed', e, data);
                    that._trigger('finished', e, data);
                    deferred.resolve();
                }
            );
        }
     }
     // Callback for file deletion:
      function destroyDone(e, data) {
          var that = $(this).data('blueimpFileupload') ||$(this).data('fileupload');
          if (data.url) {
              $.ajax(data);
              that._adjustMaxNumberOfFiles(1);
          }
          that._transition(data.context).done(
              function () {
                  $(this).remove();
                  $('#fileupload .btn-success span').html('Add Image');
                  that._trigger('destroyed', e, data);
              }
          );
      }
          // The add callback is invoked as soon as files are added to the fileupload
          // widget (via file input selection, drag & drop or add API call).
          // See the basic file upload widget for more information:
      function uploadPreview (e, data) {
        var that = $(this).data('blueimpFileupload') ||$(this).data('fileupload'),
            options = that.options,
            files = data.files;
        $(this).fileupload('process', data).done(function () {
            //Removing Errors
            $('#fileupload .template-upload').remove();

            that._adjustMaxNumberOfFiles(-files.length);
            data.isAdjusted = true;
            data.files.valid = data.isValidated = that._validate(files);
            data.context = that._renderUpload(files).data('data', data);
            options.filesContainer[
                options.prependFiles ? 'prepend' : 'append'
            ](data.context);
            that._renderPreviews(files, data.context);
            that._forceReflow(data.context);
            that._transition(data.context).done(
              function () {
                if ((that._trigger('added', e, data) !== false) && (options.autoUpload || data.autoUpload) && data.autoUpload !== false && data.isValidated) {
                  $('#fileupload .template-download').hide();
                  data.submit();
                }
              }
            );
        });
      }
    });

**Comment by felixbuenemann** [comment]
Not enough info, outdated issue.
