### ISSUE TITLE
Chunk File upload

### ISSUE THREAD

**Issue by Sabyasachig** [tors/jquery-fileupload-rails#42]
Hi,

It is possible to upload large files (more than 500 MB) using this plugin in rails 3.2.13.

Thanks
Sabyasachi

**Comment by felixbuenemann** [comment]
It is possible, but you need to ensure all intermediate components, like your web server (nginx/apache) have high enough limits set. You should also be very careful to never load the whole file into memory, which some file upload gems like carrierwave do in some situations.
