### ISSUE TITLE
On dragover preventDefault and stopPropagation doesn't work

### ISSUE THREAD

**Issue by whitesiroi** [tors/jquery-fileupload-rails#51]
Hi. 
Wanna say - AWESOME gem. Have one question.

I tried preventDefault and stopPropagation :) & still getting a lots of console.log('xxx') 

      $(function(){
        $("#msg").fileupload({
          dragover: function (e, data={preventDefault: true}) {

            if (data.preventDefault) {
              console.log('xxx');
              e.preventDefault();
              }
         }});
        })

I tried different stuff, like:
                console.log('xxx');  in front of IF
                if (data.preventDefault) {
                  e.preventDefault();
                }
and     here            console.log('xxx');

no good :)

Any help will be appreciated.
Thank you very much & Best regards,
Artem

**Comment by felixbuenemann** [comment]
Looks like the dragover event doesn't get a data parameter, so you always get your default.
