### ISSUE TITLE
progress bar is not showing any change in progress

### ISSUE THREAD

**Issue by jakehockey10** [tors/jquery-fileupload-rails#61]
Hello!  Thanks for the great gem!  I love this!  I'm hoping I can figure out basically the only issue I'm having with it: I can't get the progress bar to do what I see it do any every example application I've seen using this gem.  The upload is working, multiple files is working, the file name and progress bar appears when I use the OS dialogue to choose the files.  I even verified that the data.loaded reaches data.total.  But the progress bar does not fill with a different color.  The css width property gets set to 100% from 0% like it is supposed to.  What I'm wondering is if the progress is reaching 100% before the progress bar shows up because I placed jquery statements to display the data.loaded and data.total values every time the progress portion of the fileupload method gets called and those values only appear once and data.load is already the same as data.total.

Does anyone have an idea of what could be going wrong?  I'm not sure how to debug this...

**Comment by felixbuenemann** [comment]
Where you using IE8? When using the iframe transport the per file progress jumps form 0% to 100% with no immediate steps.

**Comment by felixbuenemann** [comment]
Closing for lack of feedback, please open a new isssue if this still happens with 0.4.2 on browsers that do support XHR uploads.

**Comment by Hareramrai** [comment]
Hi @felixbuenemann 

For me it's not working in IE 9, could you please suggest me any solution for it. 

Thanks,
Hare

**Comment by felixbuenemann** [comment]
It seems IE9 does not support XHR uploads, just like IE8:

http://caniuse.com/#feat=xhr2

**Comment by Hareramrai** [comment]
@felixbuenemann Is there any patch for progress bar to work ?

**Comment by felixbuenemann** [comment]
I don't think so, try the demos linked from https://github.com/blueimp/jquery-file-upload this repo just contains the library repackages as a ruby gem. To get progress on IE9 you'll likely have to use Flash and something like uploadify or swfupload. Unless you have a significant number of IE9 users I wouldn't bother with that.
