### ISSUE TITLE
failing to precompile assets

### ISSUE THREAD

**Issue by gajendrajena** [tors/jquery-fileupload-rails#62]
rake aborted!
Asset compilation with node failed with error:

{ [Error: Error: ENOENT, no such file or directory '/home/gajendra/projects/teamaroo/tmp/assets/load-image.js'
In module tree:
    application

    at Object.fs.openSync (fs.js:432:18)
]
  originalError: 
   { [Error: ENOENT, no such file or directory '/home/gajendra/projects/teamaroo/tmp/assets/load-image.js']
     errno: 34,
     code: 'ENOENT',
     path: '/home/gajendra/projects/teamaroo/tmp/assets/load-image.js',
     syscall: 'open',
     fileName: '/home/gajendra/projects/teamaroo/tmp/assets/load-image.js',
     moduleTree: [ 'application' ] } }

**Comment by felixbuenemann** [comment]
Can you provide more info on how you integrated the gem?

**Comment by felixbuenemann** [comment]
Closing, no further feedback provided.
