### ISSUE TITLE
0.4.1 Version Number (Feb 2013) not updated with few files which were added later the date

### ISSUE THREAD

**Issue by elitenomad** [tors/jquery-fileupload-rails#64]
0.4.1 Version Number (Feb 2013) not updated with few files which were added later the date(May 2013). Few JS files were missing in my project as i was using the version 0.4.1. I referenced git commit id to get those changes on to my project. It would be a good idea to create a new version and release it for the sake of projects on Rails 3+

**Comment by felixbuenemann** [comment]
Try 0.4.2.
