### ISSUE TITLE
Could you fix a small error in documentation

### ISSUE THREAD

**Issue by StraDIVar** [tors/jquery-fileupload-rails#71]
You use `//= require jquery-fileupload/vendor/load-image.all.min` file, not `//= require jquery-fileupload/vendor/load-image`. It may be important for those who attach files manually (like me). Fix it please

**Comment by felixbuenemann** [comment]
The git repo currently does not contain the unminified version, so the filename is correct.

**Comment by StraDIVar** [comment]
So filename in documentation is **incorrect** because there is `//= require jquery-fileupload/vendor/load-image` there

**Comment by opti** [comment]
Thanks for finding this out. Fixed via 0f83ec023ed4bfd7a108bb573772c6755269ba0c
