### ISSUE TITLE
Cant integrate S3 with javascript file upload using presigned post

### ISSUE THREAD

**Issue by moayman** [tors/jquery-fileupload-rails#77]
I have spent days now trying to make this work. I am getting this error

"OPTIONS https://bucketname.s3.oregon.amazonaws.com/net::ERR_NAME_RESOLUTION_FAILED"
When trying to upload using javascript file upload. I am using Version 43.0.2357.130 Ubuntu 14.04 (64-bit). Please check my question here http://stackoverflow.com/questions/32040619/rails-amazon-s3-direct-upload-with-jquery-file-uploader

**Comment by felixbuenemann** [comment]
There is no s3 region called "oregon", it's called us-west-2, check the aws endpoints for the proper bucket url: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by moayman** [comment]
![aws](https://cloud.githubusercontent.com/assets/8499385/9296296/7183c690-4492-11e5-901a-e31af529cddc.png)

**Comment by felixbuenemann** [comment]
Sorry, I was a bit unclear. There are two "names" for regions on AWS, the technical name, used in URLs and the descriptive name, which is a city. Eg. eu-central-1 and Frankfurt. You have to use the proper endpoint from the link I posted above.

**Comment by moayman** [comment]
It's totally okay. I just tried it today and it worked well. I was just showing you what I had to my face all time in the console which is really counter intuitive from amazon. Checkout my answer in the stackoverflow question and feel free to up me. Thanks.

**Comment by felixbuenemann** [comment]
Given that all the questions one could possibly ask are already answered on StackOverflow, I doubt I'll ever reach the 10 credits required to do anything besides reading on SO.
