### ISSUE TITLE
Update to support Rails 5.2

### ISSUE THREAD

**Issue by RailsCod3rFuture** [tors/jquery-fileupload-rails#97]
Its breaking my bundle update?
```

Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:

    jquery-fileupload-rails x64-mingw32 was resolved to 0.4.7, which depends on
      actionpack (>= 3.1) x64-mingw32

```

**Comment by felixbuenemann** [comment]
I don't see how that error relates to a Rails 5.2 incompatibility. We only depend on actionpack and actionpack 5.2.1 is `>= 3.1` so that should be fine.

You probably have a corrupt or inconsistent Gemfile.lock which is causing the error.

**Comment by RailsCod3rFuture** [comment]
It works now. I needed to update my ruby gem set to 2.4.4.
